### ISSUE TITLE
Call to undefined function ProcessWire\stringToArray()

### ISSUE THREAD

**Issue by phlppschrr** [rolandtoth/MarkupSrcSet#3]
I just installed you updated module, but unfortunately it does not work, because I get a fatal error:
`<b>Fatal error</b>:  Uncaught Error: Call to undefined function ProcessWire\stringToArray() in .../site/modules/MarkupSrcSet/MarkupSrcSet.module:123`

Btw, i really welcome your api changes!

**Comment by rolandtoth** [comment]
Oops, sorry, fixed in 0.1.1.

This method was borrowed from my other module and haven't notice it's missing because the other module was active all the time. Sorry for the inconvenience.

**Comment by phlppschrr** [comment]
Thank you!
